天気情報の取得方法を変更する
codeforchiba/feschibal pull request #340
Opened 2017-07-22 08:10 UTC by seitaro1227

- README.mdにビルド方法を追記しました。
- `grunt`に`build:staging`と`build:production`のオプションを追加しました。
- `config/staging.yml`にステージングの設定を追加しました。
- `config/production.yml`に本番環境の設定を追加しました。 
- `env.yml`はどこからも使っていなかったので削除しました。

ブランチ名をtypoしていました。`fix/weather_store`に変更しました。
https://github.com/codeforchiba/feschibal/pull/321

2017-08-02 18:55 UTC, ymits requested changes
確認しました。

このままでも要件は満たせていると思いますが、多少冗長に設定をしないといけない感じがするので、改善できるといいかなと思います。

2017-08-02 18:55 UTC, ymits commented on Gruntfile.js
> +    grunt.log.writeln(env['config_name'] + 'でbuildします。');
各環境ファイルに自分自身のファイル名を定義するのは冗長な気がするので次のような感じにするとスッキリしそうです。

```
var fileName = option + '.yml';
env = yaml.load(fs.readFileSync('config/' + fileName));
grunt.log.writeln(fileName + 'でbuildします。');
```

2017-08-02 18:55 UTC, ymits commented on config/default.yml
> +config_name: 'default.yml'
上のコメントの対応によってこのconfig_nameの定義は消したほうがスッキリすると思います。

2017-08-05 17:36 UTC, seitaro1227 commented on config/default.yml
> +config_name: 'default.yml'
レビューありがとうございます。
一先ずfileNameの件を修正しました。
確認していただけると幸いです。

2017-08-06 13:45 UTC, ymits approved these changes
修正ありがとうございます。

いいんじゃないかと思います。

2017-08-06 13:51 UTC, merged